a = (input('Digite algo aqui: '))
print('O tipo é: ', type(a))
print('É númerico?: ', a.isnumeric())
print('É alfabético?: ', a.isalpha())
print('É alfanúmerico?: ', a.isalnum())
print('Está em maiusculo?: ', a.isupper())
print('Está em minusculo?: ', a.islower())
print('Possui espaços?: ', a.isspace())
print('Está capitalizada: ', a.istitle())
print(f'É númerico?: {a.isnumeric()} \n')
